apiVersion: v1
kind: Service

metadata:
  name: backend
  namespace: taskflow
  labels:
    app: taskflow
    component: backend

spec:
  type: ClusterIP

  selector:
    app: taskflow
    component: backend

  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP