apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow

data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: taskflow
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskflow
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"