apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: taskflow
  labels:
    app: taskflow
    component: frontend

spec:
  type: NodePort

  selector:
    app: taskflow
    component: frontend

  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP