apiVersion: v1
kind: Pod
metadata:
  name: taskflow-postgres
  labels:
    app: postgres

spec:
  containers:
    - name: postgres
      image: postgres:16-alpine

      env:
        - name: POSTGRES_DB
          value: taskflow

        - name: POSTGRES_USER
          value: postgres

        - name: POSTGRES_PASSWORD
          value: devpassword

      ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432