apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: taskflow
  labels:
    app: taskflow
    component: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: taskflow
      component: postgres

  template:
    metadata:
      labels:
        app: taskflow
        component: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: taskflow-config
                  key: DATABASE_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: taskflow-db-secret
                  key: DATABASE_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskflow-db-secret
                  key: DATABASE_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc